added the network-mapper dependency
komodorio/helm-charts pull request #179
Opened 2023-04-27 13:56 UTC by shaicantor

. I had to copy the chart and just reference it since I couldn't control the namespace the mapper and sniffer were deployed since komodor hardcodes the namespace in values.yaml

2023-04-29 13:06 UTC, undera commented
I can say that I really-really don't like to copy the whole chart into our repo. Do we need the namespace to be changeable that much? In otterize's values.yaml I see there is a `namespace` value to set. Isn't it sufficient?

2023-05-01 07:59 UTC, MickaelAlliel commented on charts/k8s-watcher/values.yaml
> +  enabled: false
Merging as is is fine while disabled as default.
For the next part, I'd consider before changing the default to true (if we desire that at any point) to make sure our CI tests the installation with it both enabled/disabled on existing AND new installations of the chart.

2023-05-01 07:59 UTC, MickaelAlliel approved these changes

2023-05-01 08:00 UTC, MickaelAlliel commented
> I can say that I really-really don't like to copy the whole chart into our repo. Do we need the namespace to be changeable that much? In otterize's values.yaml I see there is a `namespace` value to set. Isn't it sufficient?

I don't like it as well, but the way the otterize's chart and our chart manages namespace is different and conflicts with one another. It will require a breaking change in our helm chart to align it (to the best-practice == letting Helm manage the namespace through `--namespace` namespaced chart and not through values)

2023-05-01 08:15 UTC, MickaelAlliel requested changes
My mistake - not sure why github checks did not see it but bump the `k8s-watcher/Chart.yaml` minor version and add to the readme config table the new keys you added to the values.yaml
You can use this https://www.tablesgenerator.com/markdown_tables or your IDE plugins to helm with the table format, manually is a bit of a pain

2023-05-01 09:32 UTC, shaicantor commented
> My mistake - not sure why github checks did not see it but bump the `k8s-watcher/Chart.yaml` minor version and add to the readme config table the new keys you added to the values.yaml You can use this https://www.tablesgenerator.com/markdown_tables or your IDE plugins to helm with the table format, manually is a bit of a pain

@MickaelAlliel , I see that the minor versions are bumped automatically, no?

2023-05-01 10:00 UTC, MickaelAlliel commented
> > My mistake - not sure why github checks did not see it but bump the `k8s-watcher/Chart.yaml` minor version and add to the readme config table the new keys you added to the values.yaml You can use this https://www.tablesgenerator.com/markdown_tables or your IDE plugins to helm with the table format, manually is a bit of a pain
> 
> @MickaelAlliel , I see that the minor versions are bumped automatically, no?

Patch version is bumped automatically.
I think adding a whole new dependency to the chart is a valid reason for minor bump :)

2023-05-01 10:05 UTC, shaicantor commented
> 

done

2023-05-01 10:10 UTC, MickaelAlliel approved these changes

2023-05-02 07:50 UTC, merged