set default values for metrics and network mapper to solve reuse-values
komodorio/helm-charts pull request #239
Opened 2023-08-22 15:24 UTC by Moran-k

2023-08-23 06:34 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/cluster-role.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 06:40 UTC, nirbenator requested changes
1. we want to enable mapper by default
2. the chart is yuck. i also don't like the version. we'll handle it next sprint

2023-08-23 06:40 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/configmap.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 06:40 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/daemonset.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 06:40 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/deployment.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 06:40 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/role.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 06:40 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/roles-binding.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 06:40 UTC, nirbenator commented on charts/k8s-watcher/templates/network-mapper/service.yaml
> +{{- if (.Values.watcher.networkMapper).enable | default false }}
```suggestion
{{- if (.Values.watcher.networkMapper).enable | default true }}
```

2023-08-23 07:34 UTC, Moran-k commented
CU-860rk698r

2023-08-24 06:53 UTC, nirbenator approved these changes

2023-08-24 07:01 UTC, merged